### ISSUE TITLE
Testbench coverage improvement

### ISSUE THREAD

**Issue by johnnyr** [RAPcores/rapcores#119]
- [ ] Need automated testbench for at least the top level. Should be able to merge the one from rapcore-caravel
- [ ] The SPI commanded motion of the rapcore-caravel testbench does not do a direction change before finish
- [ ] In addition to using SPI to drive, we need to stimulate step, dir, and enable in the test bench
- [ ] Move done state should change during the testbench

**Comment by sjkelly** [comment]
These have all been addressed for a while now.
