### ISSUE TITLE
Step out signal too short a length

### ISSUE THREAD

**Issue by johnnyr** [RAPcores/rapcores#120]
The Step out signal is very short. We should probably make the signal be on for multiple clock cycles.

**Comment by aldenhart** [comment]
Most drivers require at least 1uS, and 10uS is a better comfort zone. SOme really old drivers (like some Toshibas) want even more than that.

**Comment by sjkelly** [comment]
Some datasheet surfing:

| Part | Min Step High (ns)|
|-------|--------------------------|
| A4988 | 1000 |
|TMC2160| 100|
|DRV8825| 1900|

With #130 the pulse duration is 1/(DDA tick) currently set to 400khz so 2500ns.
